// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type CategoryLimitInput record {
    decimal monthlyLimitAmount;
};

public type Category record {
    string id;
    string name;
    # current monthly limit in the home currency
    decimal? monthlyLimitAmount?;
    # amount spent in this category this calendar month, home currency
    decimal currentMonthUsage?;
};

public type ExpenseInput record {
    string categoryId;
    decimal amount;
    # ISO 4217 currency code the expense was paid in
    string currency;
    string expenseDate;
    string? note?;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type PeriodTotals record {
    "day"|"week"|"month" period;
    string homeCurrency;
    decimal total;
    PeriodTotals_byCategory[] byCategory;
};

public type PeriodTotals_byCategory record {
    string categoryId;
    string categoryName;
    decimal amount;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type CategoryInput record {
    string name;
};

public type Expense record {
    string id;
    string categoryId;
    string enteredByMemberId?;
    decimal originalAmount;
    # ISO 4217 currency code as entered
    string originalCurrency;
    # amount converted to the household home currency
    decimal homeAmount;
    string homeCurrency;
    string expenseDate;
    string? note?;
    string createdAt?;
};

public type ExpenseListResponse record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Expense[] data;
};

public type CategoryListResponse record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Category[] data;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
